version: '3'
services:
  bot:
    build: .
    environment:
      - GIGACHAT_TOKEN=
      - BOT_TOKEN=
      - DATABASE_URL=
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=

